language: php
php:
  - 5.5
  - hhvm
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COVERAGE=1
before_script:
  - ./scripts/travis/setup.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php -i; fi"
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh